### ISSUE TITLE
db setup failed

### ISSUE THREAD

**Issue by bhanu2014** [ossfriday/ossfriday#125]
on running the command "./script/setup". The following error trace is printed in the console

```
== Preparing database ==
rails aborted!
NoMethodError: undefined method `reject' for #<String:0x007fa27e910f00>
/Users/bimarian/projects/github/ossfriday/config/application.rb:14:in `<module:Ossfriday>'
/Users/bimarian/projects/github/ossfriday/config/application.rb:13:in `<top (required)>'
/Users/bimarian/projects/github/ossfriday/Rakefile:4:in `require_relative'
/Users/bimarian/projects/github/ossfriday/Rakefile:4:in `<top (required)>'
/Users/bimarian/projects/github/ossfriday/bin/rails:9:in `require'
/Users/bimarian/projects/github/ossfriday/bin/rails:9:in `<top (required)>'
/Users/bimarian/projects/github/ossfriday/bin/spring:14:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:setup"] failed ==
```

Help me to resolve the issue

Thanks & regards
Bhanu

**Comment by MikeMcQuaid** [comment]
What's the full output of running `./script/bootstrap` then `./script/setup`? Thanks!

**Comment by MikeMcQuaid** [comment]
@bhanu2014 Also, please use triple-backticks to ensure your output is displayed correct. I've done that for you on your original post.

**Comment by MikeMcQuaid** [comment]
Sorry, can't help without that output.
